### ISSUE TITLE
[环境问题?] 报错

### ISSUE THREAD

**Issue by yiqier** [Tommy131/KuaishouParser#1]
[OwOBlogErrorHandler/EMERGENCY] > InvalidArgumentException: A non-empty PSR-4 prefix must end with a namespace separator. in /root/OwOFrame/vendor/composer/ClassLoader.php:252
Stack trace:                                                                     #0 /root/OwOFrame/src/owoframe/MasterManager.php(186): Composer\Autoload\ClassLoader->addPsr4('application/', '/root/OwOFrame/...')                               #1 /root/OwOFrame/src/owoframe/MasterManager.php(92): owoframe\MasterManager::initializeSystem()                                                                  #2 /root/OwOFrame/owo(42): owoframe\MasterManager->__construct(Object(Composer\Autoload\ClassLoader))                                                             #3 {main}

**Comment by Tommy131** [comment]
请问你使用的PHP版本是？请按照ISSUE模板发布你的问题。

**Comment by Tommy131** [comment]
该问题已在当前 `[Commit](https://github.com/Tommy131/OwOFrame/commit/66bd62c46d328dd14d1d4c17f47ebae188a79e1f)` 修复，请更新你的OwOFrame版本，感谢你的支持 ^_^
