### ISSUE TITLE
[BUG] live.kuaishou.com not using GraphQL anymore

### ISSUE THREAD

**Issue by cydevdummy001** [Tommy131/KuaishouParser#11]
## BUG description: What BUG did you encounter?
Got stuck by this request https://github.com/Tommy131/KuaishouParser/blob/master/api/User.php#L101 (not returning expected data model), hence I tried to look up the graphql request in live.kuaishou.com, but found that it is not being using at all 🤔 
## Error log / screenshot
![image](https://user-images.githubusercontent.com/118442623/220544307-bb13366f-51d1-4ccb-9190-e17db79a08b6.png)

var_dump output:
```
object(stdClass)#20 (2) {
  ["result"]=>
  int(1)
  ["message"]=>
  string(16) "活动结束啦~"
}
```

> --- Put your log or picture below ---

## How did this BUG come about?

> --- the cause of the bug ---

## Your server operating environment

> --- Environment description (e.g. below) ---
System: Windows 10
OwO-Version: latest
Web Environment:
    - Nginx 1.18.0
    - PHP 7.4
    - MySQL 5.7
    - ...

**Comment by Tommy131** [comment]
I fixed just now. Check the newest commit(s). 
Last Commit: https://github.com/Tommy131/KuaishouParser/commit/00986806842967c1f34a1ad68c5f883786b0292c

**Comment by cydevdummy001** [comment]
works like a charm now! thank you so much

**Comment by Tommy131** [comment]
> works like a charm now! thank you so much

Also thank you for using :) This is my support :)
