### ISSUE TITLE
[Question] readme中写的指令，在实际运行中不支持

### ISSUE THREAD

**Issue by hyfclimber** [Tommy131/KuaishouParser#13]
## 问题描述: 遇见了什么问题？

> --- 您的问题 ---

## 错误日志/截图
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/3303762/227778217-4c21d357-254c-43c1-8504-d0a1036300dd.png">

> --- 错误日志 ---

## 这个错误是如何产生的？

> --- 问题产生原因# 您的服务器运行环境
>
> --- 服务器环境描述(例如下方) ---
系统: Linux/CentOS 7.x
OwO版本: 开发版(v1.0.3-dev)
web环境:
    - Nginx 1.18.0
    - PHP 7.4
    - MySQL 5.7
    - ...

**Comment by hyfclimber** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/3303762/227778270-72b51405-56e8-4350-8ef3-e2060c42ea4f.png">

**Comment by Tommy131** [comment]
请仔细阅读 `README.md` 文档。请正确安装本模块后再执行指令。该问题不属于项目BUG问题。需要做的修改：
1. 检查项目是否处于 `/owoframe/storage/module/KuaishouParser` 路径
2. 若为 Linux 用户, 检查项目是否正确授予 `0755` 权限

**Comment by hyfclimber** [comment]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/3303762/227823600-abbf8ad8-1e08-434e-99b0-73edb5490cf0.png">

mac中，这个地方少一个"/"哈，导致放进/storage/module/下的module都读不出来。

**Comment by hyfclimber** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/3303762/227823844-6023009e-21e2-4855-a72f-21fa34d8885b.png">
最新的cookie，每次都读不出来，不知道什么问题哈

**Comment by Tommy131** [comment]
> <img alt="image" width="624" src="https://user-images.githubusercontent.com/3303762/227823844-6023009e-21e2-4855-a72f-21fa34d8885b.png">
> 
> 最新的cookie，每次都读不出来，不知道什么问题哈

确定ID有效？我的测试环境没有问题，如果原始ID无法请求数据，则改用快手号或者搜索用户名获取原始ID
- owo kuai -search [用户名]
- 将匹配到的第一个用户的原始ID用于请求

**Comment by Tommy131** [comment]
> <img alt="image" width="1059" src="https://user-images.githubusercontent.com/3303762/227823600-abbf8ad8-1e08-434e-99b0-73edb5490cf0.png">
> 
> mac中，这个地方少一个"/"哈，导致放进/storage/module/下的module都读不出来。

该BUG已得到验证：在Linux/MacOS系统下将无法正确加载路径。将会在OwOFrame的下一个commit修复此问题。感谢提出。

**Comment by Tommy131** [comment]
> > <img alt="image" width="1059" src="https://user-images.githubusercontent.com/3303762/227823600-abbf8ad8-1e08-434e-99b0-73edb5490cf0.png">
> > mac中，这个地方少一个"/"哈，导致放进/storage/module/下的module都读不出来。
> 
> 该BUG已得到验证：在Linux/MacOS系统下将无法正确加载路径。将会在OwOFrame的下一个commit修复此问题。感谢提出。

已提交: https://github.com/Tommy131/OwOFrame/commit/8160d44f95d243ad67afff4a2a576c0715ecbed3
