### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by zgy-beep** [Tommy131/KuaishouParser#14]
## 问题描述: 遇见了什么问题？

> 
@Tommy131 请问为什么我运行会出错呢  Syntax error: unexpected token '$_'PHP(PHP2014)

## 错误日志/截图

> ![uTools_1681139212903](https://user-images.githubusercontent.com/52773457/230929888-b8f94aaa-c186-4e31-9737-4c0c2dae2f0a.png)

## 这个错误是如何产生的？

> --- 问题产生原因# 您的服务器运行环境
>
> --- 服务器环境描述(例如下方) ---
系统: Windows 10
OwO版本: 开发版(v1.0.5-dev)
web环境:
    - Nginx 1.18.0
    - PHP 7.4
    - MySQL 5.7
    - ...

**Comment by Tommy131** [comment]
请提交你正确的PHP版本！在PHP 7.4.9已经过测试没有问题。

**Comment by zgy-beep** [comment]
我试过的版本
- PHP 7.3.4
- PHP 8.2.4
我尝试一下7.4

7.4能使用 不好意思  👍

**Comment by Tommy131** [comment]
> 我试过的版本
> - PHP 7.3.4
> - PHP 8.2.4
> 我尝试一下7.4
> 
> 7.4能使用 不好意思  👍 

感谢支持与使用！若问题已解决，请通知并关闭该issue。
