### ISSUE TITLE
安装时出现的问题

### ISSUE THREAD

**Issue by wwd7222117** [Tommy131/KuaishouParser#2]
请按照以下格式发布您的Issue。
------

#### 问题描述: 遇见了什么问题？
> --- 您的问题 ---
我再将此项目clone到application项目中后，再owoframe目录下运行php owo kuai xxxx提示我command 'kuai' not found.

#### 错误日志/截图：
[2022-06-07][20:01:05][OwOCLI/DEBUG] > Command 'kuai' not found, please use 'php owo help' to check the details

#### 这个错误是如何产生的？
因为没有学习过php相关知识，请问，怎么处理的呢，我的操作哪里除了问题，是否需要将application中的index目录进行替换呢，
辛苦辛苦，多谢

#### 您的服务器运行环境
> --- 服务器环境描述(例如下方) ---
系统: windows

**Comment by Tommy131** [comment]
你好，感谢你的使用以表示支持 :)

能否再详细一点提供操作步骤？
能否提供一下克隆到本地的kuaiApp的父级文件夹名称以及application的目录列表？
可以输入 `dir` 然后截图到此issue。

**Comment by wwd7222117** [comment]
![image](https://user-images.githubusercontent.com/33832382/172517891-abd865c8-74cc-4a0f-9b7d-4088245c6532.png)
我根据您提供的步骤，先clone owo项目，然后进行install，在这之后切换到application目录下，直接clone的此项目，然后在D:\kuaishou_downloader\OWOFRAME此目录下执行php owo kuai xxxx命令，您那看正确吗

**Comment by Tommy131** [comment]
多谢反馈。试试将文件夹名称 `KuaishouParser` 重命名为 `kuai`，再次运行对应的指令。

**Comment by Tommy131** [comment]
你好，若问题已解决，请通知并关闭当前的issue :)
