### ISSUE TITLE
请问是否有方法可以抓取到未展示出来的历史直播回放视频？

### ISSUE THREAD

**Issue by junerwong** [Tommy131/KuaishouParser#5]
**您的功能请求是否与问题有关？ 请描述。**
kuaishou直播上有些账号有展示直播回放菜单，但是有些账号没有，只能看到直播记录，但是个人感觉服务器测是有保存直播的文件的，我非常想找到解决方法，只要可行的都可以，目前我只有一点点头绪，而且我没什么开发经验.........

**描述您想要的解决方案**
能够实现功能就心满意足了。

**描述您考虑过的替代方案**
我尝试了一些土方法，我发现有些直播在结束后的大概半个小时内，会在直播回放显示出来，可能是主播可设置的，在展示出来期间，我能够通过抓包的方式找到m3u8文件，从而大概知道链接的格式，但是大部分直播都是不展示直播回放的，所以我这个土方法实际也是不太可行，主要是获取不到链接的字段值应该要传什么参数值，况且我要找的回放是一两个月以前的（希望服务器还未删除）......我非常想找到解决方案，不知道博主对这个有没有兴趣？我这边可以进一步详细描述...

**附加上下文**
---在此处添加有关功能请求的任何其他上下文或屏幕截图---

**Comment by Tommy131** [comment]
感谢支持。最近因个人原因没来得及更新项目，等过段时间我研究下这个提议。

**Comment by Tommy131** [comment]
用户 @junerwong 你好，非常感谢你对本项目的支持。由于技术问题，可能会让你对此功能不抱有任何希望。

- 通过抓包快手官方的 `直播回放` 接口，只能够获取主播公开的直播回放。
-  若主播设置了隐藏回放，则无法获取回放记录。
-  我可以尝试开发该功能，但也仅限于：当目标用户的直播回放记录为 `开启状态` 时，即可获取该用户的直播回放。

**Comment by Tommy131** [comment]
该Issue关闭原因：
- 发布者未在5天内回复
- 期望工程不在项目开发计划内
若发布者对该处理结果存有异议，请重新打开该Issue并在下方继续提交请求。
