### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by ayccc** [Tommy131/KuaishouParser#8]
正在登录到平台: kuaishou.server.web
[2022-09-22][14:21:35][OwOBlogErrorHandler/EMERGENCY] > Error: Call to undefined function owoframe\network\curl_init() in /root/git/OwOFrame/src/owoframe/network/Curl.php:111
Stack trace:
#0 /root/git/OwOFrame/application/kuai/command/KuaiCommand.php(590): owoframe\network\Curl->__construct()
#1 /root/git/OwOFrame/application/kuai/command/KuaiCommand.php(347): application\kuai\command\KuaiCommand->initCurl()
#2 /root/git/OwOFrame/application/kuai/command/KuaiCommand.php(56): application\kuai\command\KuaiCommand->interceptParameters()
#3 /root/git/OwOFrame/src/owoframe/console/Console.php(116): application\kuai\command\KuaiCommand->execute()
#4 /root/git/OwOFrame/owo(29): owoframe\console\Console->monitor()
#5 {main}

**Comment by iGoogleVip** [comment]
[2022-09-23][00:58:38][Console/INFO] > 正在查询......
[2022-09-23][00:58:38][OwOBlogErrorHandler/EMERGENCY] > TypeError: Return value of application\kuai\api\Graphql::getResult() must be an instance of application\kuai\api\Graphql or null, instance of stdClass returned in /root/OwOFrame/application/kuai/api/Graphql.php:149
Stack trace:
#0 /root/OwOFrame/application/kuai/command/KuaiCommand.php(83): application\kuai\api\Graphql->getResult()
#1 /root/OwOFrame/src/owoframe/console/Console.php(116): application\kuai\command\KuaiCommand->execute()
#2 /root/OwOFrame/owo(29): owoframe\console\Console->monitor()
#3 {main}

**Comment by iGoogleVip** [comment]
the same bug , can't work

**Comment by Tommy131** [comment]
Thanks for the issue, I'll fix it in the next commit.

**Comment by Tommy131** [comment]
@iGoogleVip @ayccc  check the newest version with [OwOFrame](https://github.com/Tommy131/OwOFrame/) and KuaishouParser. If that works, then you can safely close this issue please :) Commit: 23314ebeace23bac61a18536ba8e81bc5b21655a

**Comment by Tommy131** [comment]
请在之后的Issue中使用标准模板。Please use the standard Issue template for the future.

**Comment by Tommy131** [comment]
This Issue will be closed because of:
- The author has not responded within 5 days.

**Comment by Tommy131** [comment]
> the same bug , can't work

I was compare yours issue and this again, it was not the same bug. @ayccc This bug causes because the PHP environment has not enabled the `Curl` extension, so that cannot find the function `curl_init`. @ayccc PLEASE CHECK YOUR PHP ENVIRONMENT!!!
