### ISSUE TITLE
[2022-09-23][00:58:38][Console/INFO] > 正在查询......

### ISSUE THREAD

**Issue by iGoogleVip** [Tommy131/KuaishouParser#9]
[2022-09-23][00:58:38][Console/INFO] > 正在查询......
[2022-09-23][00:58:38][OwOBlogErrorHandler/EMERGENCY] > TypeError: Return value of application\kuai\api\Graphql::getResult() must be an instance of application\kuai\api\Graphql or null, instance of stdClass returned in /root/OwOFrame/application/kuai/api/Graphql.php:149
Stack trace:
#0 /root/OwOFrame/application/kuai/command/KuaiCommand.php(83): application\kuai\api\Graphql->getResult()
#1 /root/OwOFrame/src/owoframe/console/Console.php(116): application\kuai\command\KuaiCommand->execute()
#2 /root/OwOFrame/owo(29): owoframe\console\Console->monitor()
#3 {main}

_Originally posted by @iGoogleVip in https://github.com/Tommy131/KuaishouParser/issues/8#issuecomment-1255647746_

**Comment by Tommy131** [comment]
Thanks for the issue, I'll fix it in the next commit.

**Comment by Tommy131** [comment]
@iGoogleVip  check the newest version with [OwOFrame](https://github.com/Tommy131/OwOFrame/) and KuaishouParser. If that works, then you can safely close this issue please :) Commit: 23314ebeace23bac61a18536ba8e81bc5b21655a

**Comment by Tommy131** [comment]
请在之后的Issue中使用标准模板。Please use the standard Issue template for the future.

**Comment by iGoogleVip** [comment]
thank u very much, u are so great

**Comment by Tommy131** [comment]
> thank u very much, u are so great

If that is works, you can close this issue.

**Comment by Tommy131** [comment]
This Issue will be closed because of:
- The author has not responded within 5 days.
- Bug had fixed.
